version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: rootdb@server
      MARIADB_DATABASE: database
      MARIADB_USER: root
      MARIADB_PASSWORD: rootdb@database
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
