version: "3.1"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootdb@server
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - mydbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootdb@server
    ports:
      - 8080:80
    depends_on:
      - mysqldb

volumes:
  mydbdata:
